// ═══ COMPREHENSIVE US CITY DATA ═══
// CA cities have individual tax rates where known; default 1.25% for others.
// Non-CA states use state-level average rates (from STATE_PROPERTY_TAX_RATES in main file).

export const CA_CITY_TAX_RATES = {
 // ── Existing known rates (Bay Area + Wine Country + key metros) ──
 "Alameda": 0.012127, "Alamo": 0.010826, "Albany": 0.013571, "Alhambra Valley": 0.011224,
 "Amador Valley": 0.01139, "American Canyon": 0.000217, "Antioch": 0.010492, "Ashland": 0.011946,
 "Atherton": 0.010913, "Bay Point": 0.011023, "Bayview": 0.011023, "Belmont": 0.011247,
 "Belvedere": 0.010931, "Benicia": 0.01157, "Berkeley": 0.012323, "Bethel Island": 0.010876,
 "Blackhawk": 0.010876, "Bolinas": 0.010911, "Brentwood": 0.011045, "Briones": 0.011556,
 "Brisbane": 0.010921, "Broadmoor": 0.011494, "Burlingame": 0.011196, "Byron": 0.010964,
 "Calistoga": 0.000309, "Camino Tassajara": 0.010824, "Campbell": 0.011973, "Castro Valley": 0.011946,
 "Clayton": 0.010994, "Cloverdale": 0.010989, "Colma": 0.01116, "Concord": 0.011161,
 "Corte Madera": 0.011084, "Cotati": 0.011148, "Cupertino": 0.012076, "Daly City": 0.011369,
 "Danville": 0.010826, "Discovery Bay": 0.010964, "Dublin": 0.011515, "East Palo Alto": 0.011534,
 "El Cerrito": 0.013033, "El Sobrante": 0.012161, "Emeryville": 0.012469, "Fairfax": 0.010963,
 "Fairfield": 0.011558, "Foster City": 0.011274, "Fremont": 0.011987, "Gilroy": 0.011919,
 "Half Moon Bay": 0.011126, "Hayward": 0.012265, "Healdsburg": 0.010989, "Hercules": 0.011556,
 "Hillsborough": 0.010901, "Kensington": 0.013033, "Knightsen": 0.010964, "Lafayette": 0.011081,
 "Lagunitas": 0.010911, "Larkspur": 0.011089, "Livermore": 0.011752, "Los Altos": 0.011519,
 "Los Altos Hills": 0.011369, "Los Gatos": 0.011813, "Martinez": 0.011224, "Menlo Park": 0.011199,
 "Mill Valley": 0.011065, "Millbrae": 0.011274, "Milpitas": 0.012193, "Monte Sereno": 0.011813,
 "Moraga": 0.011203, "Morgan Hill": 0.01186, "Mountain View": 0.012018, "Napa": 0.011387,
 "Newark": 0.012081, "Nicasio": 0.010911, "Novato": 0.011233, "Oakland": 0.013671,
 "Oakley": 0.011045, "Orinda": 0.011068, "Pacifica": 0.011369, "Palo Alto": 0.011359,
 "Petaluma": 0.011148, "Piedmont": 0.012785, "Pinole": 0.011556, "Pittsburg": 0.011204,
 "Pleasant Hill": 0.011073, "Pleasanton": 0.011471, "Portola Valley": 0.01086,
 "Redwood City": 0.011534, "Richmond": 0.013138, "Rodeo": 0.011556, "Rohnert Park": 0.011148,
 "Ross": 0.010931, "San Anselmo": 0.010963, "San Bruno": 0.011369, "San Carlos": 0.011247,
 "San Francisco": 0.011665, "San Jose": 0.012076, "San Leandro": 0.012081, "San Lorenzo": 0.011946,
 "San Mateo": 0.011274, "San Pablo": 0.013138, "San Rafael": 0.011065, "San Ramon": 0.010826,
 "Santa Clara": 0.012076, "Santa Rosa": 0.010989, "Saratoga": 0.011813, "Sausalito": 0.011065,
 "Sebastopol": 0.010989, "Sonoma": 0.011148, "South San Francisco": 0.011369,
 "Sunnyvale": 0.012018, "Tiburon": 0.010931, "Union City": 0.012081, "Vacaville": 0.011558,
 "Vallejo": 0.011558, "Walnut Creek": 0.011023, "Windsor": 0.010989, "Woodside": 0.01086,
 // ── All other CA incorporated cities (default 1.25%) ──
 "Adelanto": 0.0125, "Agoura Hills": 0.0125, "Alhambra": 0.0125, "Alturas": 0.0125,
 "Amador City": 0.0125, "Anaheim": 0.0125, "Anderson": 0.0125, "Angels Camp": 0.0125,
 "Apple Valley": 0.0125, "Arcadia": 0.0125, "Arcata": 0.0125, "Arroyo Grande": 0.0125,
 "Artesia": 0.0125, "Arvin": 0.0125, "Atascadero": 0.0125, "Atwater": 0.0125,
 "Auburn": 0.0125, "Avalon": 0.0125, "Avenal": 0.0125, "Azusa": 0.0125,
 "Bakersfield": 0.0125, "Baldwin Park": 0.0125, "Banning": 0.0125, "Barstow": 0.0125,
 "Beaumont": 0.0125, "Bell": 0.0125, "Bell Gardens": 0.0125, "Bellflower": 0.0125,
 "Belvedere": 0.010931, "Benicia": 0.01157, "Beverly Hills": 0.0125, "Big Bear Lake": 0.0125,
 "Biggs": 0.0125, "Bishop": 0.0125, "Blue Lake": 0.0125, "Blythe": 0.0125,
 "Bradbury": 0.0125, "Brawley": 0.0125, "Brea": 0.0125, "Buellton": 0.0125,
 "Buena Park": 0.0125, "Burbank": 0.0125, "Calabasas": 0.0125, "Calexico": 0.0125,
 "California City": 0.0125, "Calimesa": 0.0125, "Camarillo": 0.0125, "Canyon Lake": 0.0125,
 "Capitola": 0.0125, "Carlsbad": 0.0125, "Carmel-by-the-Sea": 0.0125, "Carson": 0.0125,
 "Cathedral City": 0.0125, "Ceres": 0.0125, "Cerritos": 0.0125, "Chico": 0.0125,
 "Chino": 0.0125, "Chino Hills": 0.0125, "Chowchilla": 0.0125, "Chula Vista": 0.0125,
 "Citrus Heights": 0.0125, "Claremont": 0.0125, "Clovis": 0.0125, "Coachella": 0.0125,
 "Coalinga": 0.0125, "Colfax": 0.0125, "Colton": 0.0125, "Colusa": 0.0125,
 "Commerce": 0.0125, "Compton": 0.0125, "Corcoran": 0.0125, "Corning": 0.0125,
 "Corona": 0.0125, "Coronado": 0.0125, "Costa Mesa": 0.0125, "Covina": 0.0125,
 "Crescent City": 0.0125, "Cudahy": 0.0125, "Culver City": 0.0125, "Cypress": 0.0125,
 "Dana Point": 0.0125, "Davis": 0.0125, "Del Mar": 0.0125, "Del Rey Oaks": 0.0125,
 "Delano": 0.0125, "Desert Hot Springs": 0.0125, "Diamond Bar": 0.0125, "Dinuba": 0.0125,
 "Dixon": 0.0125, "Dorris": 0.0125, "Dos Palos": 0.0125, "Downey": 0.0125,
 "Duarte": 0.0125, "Dunsmuir": 0.0125, "East Palo Alto": 0.011534,
 "Eastvale": 0.0125, "El Cajon": 0.0125, "El Centro": 0.0125, "El Monte": 0.0125,
 "El Segundo": 0.0125, "Elk Grove": 0.0125, "Encinitas": 0.0125, "Escalon": 0.0125,
 "Escondido": 0.0125, "Etna": 0.0125, "Eureka": 0.0125, "Exeter": 0.0125,
 "Farmersville": 0.0125, "Ferndale": 0.0125, "Fillmore": 0.0125, "Firebaugh": 0.0125,
 "Folsom": 0.0125, "Fontana": 0.0125, "Fort Bragg": 0.0125, "Fort Jones": 0.0125,
 "Fortuna": 0.0125, "Fountain Valley": 0.0125, "Fowler": 0.0125, "Fresno": 0.0125,
 "Fullerton": 0.0125, "Galt": 0.0125, "Garden Grove": 0.0125, "Gardena": 0.0125,
 "Ghent": 0.0125, "Glendale": 0.0125, "Glendora": 0.0125, "Goleta": 0.0125,
 "Gonzales": 0.0125, "Grand Terrace": 0.0125, "Grass Valley": 0.0125, "Greenfield": 0.0125,
 "Gridley": 0.0125, "Grover Beach": 0.0125, "Guadalupe": 0.0125, "Gustine": 0.0125,
 "Hanford": 0.0125, "Hawaiian Gardens": 0.0125, "Hawthorne": 0.0125,
 "Hemet": 0.0125, "Hermosa Beach": 0.0125, "Hesperia": 0.0125, "Hidden Hills": 0.0125,
 "Highland": 0.0125, "Hollister": 0.0125, "Holtville": 0.0125, "Hughson": 0.0125,
 "Huntington Beach": 0.0125, "Huntington Park": 0.0125, "Huron": 0.0125,
 "Imperial": 0.0125, "Imperial Beach": 0.0125, "Indian Wells": 0.0125, "Indio": 0.0125,
 "Industry": 0.0125, "Inglewood": 0.0125, "Ione": 0.0125, "Irvine": 0.0125,
 "Irwindale": 0.0125, "Isleton": 0.0125, "Jackson": 0.0125, "Jurupa Valley": 0.0125,
 "Kerman": 0.0125, "King City": 0.0125, "Kingsburg": 0.0125,
 "La Canada Flintridge": 0.0125, "La Habra": 0.0125, "La Habra Heights": 0.0125,
 "La Mesa": 0.0125, "La Mirada": 0.0125, "La Palma": 0.0125, "La Puente": 0.0125,
 "La Quinta": 0.0125, "La Verne": 0.0125, "Laguna Beach": 0.0125, "Laguna Hills": 0.0125,
 "Laguna Niguel": 0.0125, "Laguna Woods": 0.0125, "Lake Elsinore": 0.0125,
 "Lake Forest": 0.0125, "Lakeport": 0.0125, "Lakewood": 0.0125, "Lancaster": 0.0125,
 "Lathrop": 0.0125, "Lawndale": 0.0125, "Lemon Grove": 0.0125, "Lemoore": 0.0125,
 "Lincoln": 0.0125, "Lindsay": 0.0125, "Live Oak": 0.0125, "Lodi": 0.0125,
 "Loma Linda": 0.0125, "Lomita": 0.0125, "Lompoc": 0.0125, "Long Beach": 0.0125,
 "Los Alamitos": 0.0125, "Los Angeles": 0.0125, "Los Banos": 0.0125, "Los Gatos": 0.011813,
 "Loyalton": 0.0125, "Lynwood": 0.0125, "Madera": 0.0125, "Malibu": 0.0125,
 "Mammoth Lakes": 0.0125, "Manhattan Beach": 0.0125, "Manteca": 0.0125, "Maricopa": 0.0125,
 "Marina": 0.0125, "Maywood": 0.0125, "McFarland": 0.0125, "Mendota": 0.0125,
 "Menifee": 0.0125, "Merced": 0.0125, "Mission Viejo": 0.0125, "Modesto": 0.0125,
 "Monrovia": 0.0125, "Montague": 0.0125, "Montclair": 0.0125, "Monte Sereno": 0.011813,
 "Montebello": 0.0125, "Monterey": 0.0125, "Monterey Park": 0.0125, "Moorpark": 0.0125,
 "Moreno Valley": 0.0125, "Morro Bay": 0.0125, "Mount Shasta": 0.0125,
 "Mountain House": 0.0125, "Murrieta": 0.0125, "National City": 0.0125,
 "Needles": 0.0125, "Nevada City": 0.0125, "Newman": 0.0125, "Newport Beach": 0.0125,
 "Norco": 0.0125, "Norman": 0.0125, "Norwalk": 0.0125,
 "Oakdale": 0.0125, "Oceanside": 0.0125, "Ojai": 0.0125, "Ontario": 0.0125,
 "Orange": 0.0125, "Orange Cove": 0.0125, "Orland": 0.0125, "Oroville": 0.0125,
 "Oxnard": 0.0125, "Pacific Grove": 0.0125, "Palmdale": 0.0125, "Palm Desert": 0.0125,
 "Palm Springs": 0.0125, "Palos Verdes Estates": 0.0125, "Paradise": 0.0125,
 "Paramount": 0.0125, "Parlier": 0.0125, "Pasadena": 0.0125, "Paso Robles": 0.0125,
 "Patterson": 0.0125, "Perris": 0.0125, "Pico Rivera": 0.0125, "Placentia": 0.0125,
 "Placerville": 0.0125, "Plymouth": 0.0125, "Point Arena": 0.0125, "Pomona": 0.0125,
 "Port Hueneme": 0.0125, "Porterville": 0.0125, "Poway": 0.0125,
 "Rancho Cordova": 0.0125, "Rancho Cucamonga": 0.0125, "Rancho Mirage": 0.0125,
 "Rancho Palos Verdes": 0.0125, "Rancho Santa Margarita": 0.0125,
 "Red Bluff": 0.0125, "Redding": 0.0125, "Redlands": 0.0125, "Redondo Beach": 0.0125,
 "Reedley": 0.0125, "Rialto": 0.0125, "Ridgecrest": 0.0125, "Rio Dell": 0.0125,
 "Rio Vista": 0.0125, "Ripon": 0.0125, "Riverbank": 0.0125, "Riverside": 0.0125,
 "Rocklin": 0.0125, "Rolling Hills": 0.0125, "Rolling Hills Estates": 0.0125,
 "Rosemead": 0.0125, "Roseville": 0.0125, "Sacramento": 0.0125,
 "Salinas": 0.0125, "San Bernardino": 0.0125, "San Clemente": 0.0125,
 "San Diego": 0.0125, "San Dimas": 0.0125, "San Fernando": 0.0125,
 "San Gabriel": 0.0125, "San Jacinto": 0.0125, "San Juan Bautista": 0.0125,
 "San Juan Capistrano": 0.0125, "San Luis Obispo": 0.0125, "San Marcos": 0.0125,
 "San Marino": 0.0125, "Sand City": 0.0125, "Sanger": 0.0125,
 "Santa Ana": 0.0125, "Santa Barbara": 0.0125, "Santa Clarita": 0.0125,
 "Santa Cruz": 0.0125, "Santa Fe Springs": 0.0125, "Santa Maria": 0.0125,
 "Santa Monica": 0.0125, "Santa Paula": 0.0125, "Santee": 0.0125,
 "Scotts Valley": 0.0125, "Seal Beach": 0.0125, "Seaside": 0.0125,
 "Selma": 0.0125, "Shafter": 0.0125, "Shasta Lake": 0.0125, "Sierra Madre": 0.0125,
 "Signal Hill": 0.0125, "Simi Valley": 0.0125, "Solana Beach": 0.0125,
 "Soledad": 0.0125, "Solvang": 0.0125, "South El Monte": 0.0125,
 "South Gate": 0.0125, "South Lake Tahoe": 0.0125, "South Pasadena": 0.0125,
 "Stanton": 0.0125, "Stockton": 0.0125, "Suisun City": 0.0125,
 "Susanville": 0.0125, "Sutter Creek": 0.0125, "Taft": 0.0125, "Tehachapi": 0.0125,
 "Tehama": 0.0125, "Temecula": 0.0125, "Temple City": 0.0125, "Thousand Oaks": 0.0125,
 "Torrance": 0.0125, "Tracy": 0.0125, "Trinidad": 0.0125, "Truckee": 0.0125,
 "Tulare": 0.0125, "Turlock": 0.0125, "Tustin": 0.0125, "Twentynine Palms": 0.0125,
 "Ukiah": 0.0125, "Upland": 0.0125, "Vacaville": 0.011558, "Ventura": 0.0125,
 "Vernon": 0.0125, "Victorville": 0.0125, "Villa Park": 0.0125, "Visalia": 0.0125,
 "Vista": 0.0125, "Walnut": 0.0125, "Wasco": 0.0125, "Waterford": 0.0125,
 "Watsonville": 0.0125, "Weed": 0.0125, "West Covina": 0.0125, "West Hollywood": 0.0125,
 "West Sacramento": 0.0125, "Westlake Village": 0.0125, "Westminster": 0.0125,
 "Westmorland": 0.0125, "Wheatland": 0.0125, "Whittier": 0.0125, "Wildomar": 0.0125,
 "Williams": 0.0125, "Willits": 0.0125, "Willows": 0.0125, "Winters": 0.0125,
 "Woodlake": 0.0125, "Woodland": 0.0125, "Yorba Linda": 0.0125, "Yountville": 0.0125,
 "Yreka": 0.0125, "Yuba City": 0.0125, "Yucaipa": 0.0125, "Yucca Valley": 0.0125,
};

// Sorted CA city names for dropdown
export const CA_CITY_NAMES = Object.keys(CA_CITY_TAX_RATES).sort();

// ═══ CITIES BY STATE (non-CA) ═══
// Major cities per state for the city dropdown. Users can also type custom city names.
export const STATE_CITIES = {
 "Alabama": ["Alabaster","Albertville","Alexander City","Anniston","Athens","Atmore","Auburn","Bessemer","Birmingham","Center Point","Chelsea","Cullman","Daphne","Decatur","Dothan","Enterprise","Eufaula","Fairhope","Florence","Foley","Fort Payne","Gadsden","Gardendale","Hartselle","Helena","Homewood","Hoover","Hueytown","Huntsville","Jacksonville","Jasper","Leeds","Madison","Mobile","Montgomery","Mountain Brook","Muscle Shoals","Northport","Opelika","Oxford","Ozark","Pelham","Phenix City","Prattville","Prichard","Saraland","Scottsboro","Selma","Talladega","Tallassee","Troy","Trussville","Tuscaloosa","Vestavia Hills"],
 "Alaska": ["Anchorage","Badger","Bethel","College","Fairbanks","Juneau","Kenai","Ketchikan","Kodiak","Nome","Palmer","Sitka","Soldotna","Wasilla"],
 "Arizona": ["Apache Junction","Avondale","Buckeye","Bullhead City","Casa Grande","Casas Adobes","Catalina Foothills","Cave Creek","Chandler","Cottonwood","Douglas","El Mirage","Eloy","Flagstaff","Florence","Flowing Wells","Fortuna Foothills","Fountain Hills","Gilbert","Glendale","Globe","Goodyear","Green Valley","Kingman","Lake Havasu City","Laveen","Litchfield Park","Marana","Maricopa","Mesa","Nogales","Oro Valley","Paradise Valley","Payson","Peoria","Phoenix","Prescott","Prescott Valley","Queen Creek","Sahuarita","San Luis","San Tan Valley","Scottsdale","Sedona","Show Low","Sierra Vista","Somerton","Sun City","Sun City West","Surprise","Tempe","Tucson","Yuma"],
 "Arkansas": ["Arkadelphia","Batesville","Bella Vista","Benton","Bentonville","Blytheville","Bryant","Cabot","Camden","Centerton","Cherokee Village","Conway","Crossett","El Dorado","Fayetteville","Forrest City","Fort Smith","Harrison","Helena-West Helena","Hope","Hot Springs","Jacksonville","Jonesboro","Little Rock","Lowell","Maumelle","Mena","Mountain Home","North Little Rock","Paragould","Pine Bluff","Rogers","Russellville","Searcy","Sherwood","Siloam Springs","Springdale","Stuttgart","Texarkana","Van Buren","West Memphis"],
 "Colorado": ["Arvada","Aurora","Boulder","Brighton","Broomfield","Canon City","Castle Rock","Centennial","Cherry Hills Village","Colorado Springs","Commerce City","Denver","Durango","Englewood","Erie","Evans","Federal Heights","Fort Collins","Fountain","Golden","Grand Junction","Greeley","Greenwood Village","Highlands Ranch","Johnstown","Lafayette","Lakewood","Littleton","Longmont","Louisville","Loveland","Montrose","Northglenn","Parker","Pueblo","Security-Widefield","Steamboat Springs","Sterling","Superior","Thornton","Westminster","Wheat Ridge","Windsor"],
 "Connecticut": ["Ansonia","Berlin","Bloomfield","Branford","Bridgeport","Bristol","Cheshire","Clinton","Danbury","Darien","Derby","East Hartford","East Haven","Enfield","Fairfield","Farmington","Glastonbury","Greenwich","Groton","Guilford","Hamden","Hartford","Manchester","Meriden","Middletown","Milford","Monroe","Naugatuck","New Britain","New Canaan","New Haven","New London","New Milford","Newington","Newtown","North Haven","Norwalk","Norwich","Orange","Ridgefield","Shelton","Simsbury","South Windsor","Southington","Stamford","Stratford","Torrington","Trumbull","Vernon","Wallingford","Waterbury","West Hartford","West Haven","Westport","Wethersfield","Windham","Windsor"],
 "Delaware": ["Bear","Brookside","Camden","Claymont","Delaware City","Dover","Elsmere","Georgetown","Glasgow","Hockessin","Lewes","Middletown","Milford","Millsboro","New Castle","Newark","North Star","Pike Creek","Rehoboth Beach","Seaford","Smyrna","Wilmington"],
 "District of Columbia": ["Washington"],
 "Florida": ["Altamonte Springs","Apopka","Aventura","Boca Raton","Bonita Springs","Boynton Beach","Bradenton","Brandon","Cape Coral","Casselberry","Clearwater","Clermont","Coconut Creek","Cooper City","Coral Gables","Coral Springs","Crestview","Cutler Bay","Davie","Daytona Beach","Deerfield Beach","DeLand","Delray Beach","Deltona","Doral","Dunedin","Fort Lauderdale","Fort Myers","Fort Pierce","Gainesville","Greenacres","Haines City","Hallandale Beach","Hialeah","Hollywood","Homestead","Jacksonville","Jupiter","Kendale Lakes","Kendall","Key West","Kissimmee","Lake Worth Beach","Lakeland","Largo","Lauderhill","Leesburg","Margate","Melbourne","Miami","Miami Beach","Miami Gardens","Miami Lakes","Miramar","Naples","North Lauderdale","North Miami","North Miami Beach","North Port","Oakland Park","Ocala","Ocoee","Orlando","Ormond Beach","Oviedo","Palatka","Palm Bay","Palm Beach Gardens","Palm Coast","Palm Harbor","Palmetto Bay","Panama City","Pembroke Pines","Pensacola","Pinellas Park","Plant City","Plantation","Poinciana","Pompano Beach","Port Charlotte","Port Orange","Port St. Lucie","Riverview","Royal Palm Beach","Sanford","Sarasota","Spring Hill","St. Augustine","St. Cloud","St. Petersburg","Sunrise","Sweetwater","Tallahassee","Tamarac","Tampa","Tarpon Springs","The Hammocks","Titusville","Venice","Wellington","Wesley Chapel","West Palm Beach","Weston","Winter Garden","Winter Haven","Winter Park","Winter Springs"],
 "Georgia": ["Acworth","Albany","Alpharetta","Athens","Atlanta","Augusta","Brookhaven","Brunswick","Canton","Carrollton","Cartersville","Chamblee","Columbus","Conyers","Covington","Dalton","Decatur","Douglasville","Dublin","Duluth","Dunwoody","East Point","Evans","Fayetteville","Gainesville","Griffin","Hampton","Hinesville","Johns Creek","Kennesaw","Kingsland","LaGrange","Lawrenceville","Macon","Marietta","McDonough","Milledgeville","Milton","Newnan","Norcross","Peachtree City","Peachtree Corners","Perry","Pooler","Richmond Hill","Rome","Roswell","Sandy Springs","Savannah","Smyrna","Snellville","Statesboro","Stockbridge","Stonecrest","Sugar Hill","Suwanee","Tucker","Valdosta","Warner Robins","Woodstock"],
 "Hawaii": ["Ewa Beach","Hilo","Honolulu","Kahului","Kailua","Kapolei","Kaneohe","Lahaina","Lihue","Mililani Town","Pearl City","Waipahu"],
 "Idaho": ["Ammon","Blackfoot","Boise","Burley","Caldwell","Chubbuck","Coeur d'Alene","Eagle","Garden City","Hayden","Idaho Falls","Jerome","Kuna","Lewiston","Meridian","Moscow","Mountain Home","Nampa","Pocatello","Post Falls","Rexburg","Star","Twin Falls"],
 "Illinois": ["Addison","Algonquin","Alton","Arlington Heights","Aurora","Bartlett","Batavia","Belleville","Berwyn","Bloomington","Bolingbrook","Buffalo Grove","Burbank","Calumet City","Carbondale","Carol Stream","Carpentersville","Champaign","Chicago","Cicero","Collinsville","Crystal Lake","Danville","Decatur","DeKalb","Des Plaines","Downers Grove","East St. Louis","Edwardsville","Effingham","Elgin","Elk Grove Village","Elmhurst","Evanston","Galesburg","Geneva","Glen Ellyn","Glendale Heights","Glenview","Granite City","Gurnee","Hanover Park","Hoffman Estates","Homer Glen","Huntley","Joliet","Kankakee","Lake in the Hills","Lake Zurich","Lansing","Libertyville","Lisle","Lockport","Lombard","McHenry","Moline","Mount Prospect","Mundelein","Naperville","New Lenox","Niles","Normal","North Aurora","Northbrook","O'Fallon","Oak Forest","Oak Lawn","Oak Park","Orland Park","Oswego","Palatine","Park Ridge","Pekin","Peoria","Plainfield","Quincy","Rock Island","Rockford","Rolling Meadows","Romeoville","Round Lake Beach","Schaumburg","Shorewood","Skokie","Springfield","St. Charles","Streamwood","Tinley Park","Urbana","Vernon Hills","Waukegan","Wheaton","Wheeling","Wilmette","Woodridge","Woodstock"],
 "Indiana": ["Anderson","Avon","Bloomington","Brownsburg","Carmel","Clarksville","Columbus","Crown Point","Dyer","East Chicago","Elkhart","Evansville","Fishers","Fort Wayne","Franklin","Gary","Goshen","Greenfield","Greenwood","Granger","Hammond","Highland","Hobart","Indianapolis","Jeffersonville","Kokomo","Lafayette","Lake Station","Lawrence","Lebanon","Logansport","Marion","Martinsville","Merrillville","Michigan City","Mishawaka","Muncie","Munster","Noblesville","New Albany","New Castle","Plainfield","Portage","Richmond","Schererville","Shelbyville","South Bend","Terre Haute","Valparaiso","Vincennes","West Lafayette","Westfield","Zionsville"],
 "Iowa": ["Ames","Ankeny","Bettendorf","Boone","Burlington","Cedar Falls","Cedar Rapids","Clinton","Clive","Coralville","Council Bluffs","Davenport","Des Moines","Dubuque","Fort Dodge","Grimes","Indianola","Iowa City","Johnston","Keokuk","Marion","Marshalltown","Mason City","Muscatine","Newton","North Liberty","Norwalk","Ottumwa","Sioux City","Spencer","Urbandale","Waukee","Waterloo","Waverly","West Des Moines"],
 "Kansas": ["Andover","Arkansas City","Atchison","Chanute","Derby","Dodge City","El Dorado","Emporia","Garden City","Gardner","Great Bend","Hays","Hutchinson","Junction City","Kansas City","Lansing","Lawrence","Leavenworth","Leawood","Lenexa","Liberal","Manhattan","McPherson","Merriam","Mission","Newton","Olathe","Ottawa","Overland Park","Parsons","Pittsburgh","Prairie Village","Salina","Shawnee","Topeka","Wichita","Winfield"],
 "Kentucky": ["Ashland","Bardstown","Berea","Bowling Green","Burlington","Covington","Danville","Elizabethtown","Erlanger","Florence","Fort Thomas","Frankfort","Georgetown","Glasgow","Henderson","Hopkinsville","Independence","Jeffersontown","Lexington","Louisville","Madisonville","Murray","Nicholasville","Owensboro","Paducah","Radcliff","Richmond","Shelbyville","Somerset","St. Matthews","Winchester"],
 "Louisiana": ["Alexandria","Baker","Baton Rouge","Bossier City","Broussard","Central","Covington","Denham Springs","DeRidder","Gonzales","Gretna","Hammond","Harvey","Houma","Kenner","Lafayette","Lake Charles","Laplace","Mandeville","Marrero","Metairie","Minden","Monroe","Natchitoches","New Iberia","New Orleans","Opelousas","Prairieville","Ruston","Shreveport","Slidell","Sulphur","Terrytown","Thibodaux","West Monroe","Youngsville","Zachary"],
 "Maine": ["Auburn","Augusta","Bangor","Bath","Biddeford","Brewer","Brunswick","Caribou","Ellsworth","Falmouth","Gardiner","Gorham","Kennebunk","Lewiston","Old Orchard Beach","Old Town","Portland","Presque Isle","Saco","Sanford","Scarborough","South Portland","Waterville","Westbrook","Windham","Yarmouth"],
 "Maryland": ["Aberdeen","Annapolis","Baltimore","Bel Air","Bethesda","Bowie","Catonsville","Chesapeake Beach","Chestertown","Clarksburg","College Park","Columbia","Cumberland","Dundalk","Easton","Eldersburg","Elkridge","Elkton","Ellicott City","Essex","Frederick","Gaithersburg","Germantown","Glen Burnie","Greenbelt","Hagerstown","Havre de Grace","Hyattsville","Jessup","Laurel","Middle River","Millersville","Odenton","Olney","Owings Mills","Oxon Hill","Pasadena","Pikesville","Potomac","Randallstown","Rockville","Salisbury","Severn","Severna Park","Silver Spring","Takoma Park","Towson","Waldorf","Westminster","Wheaton","Woodlawn"],
 "Massachusetts": ["Agawam","Amherst","Arlington","Attleboro","Barnstable","Beverly","Boston","Braintree","Bridgewater","Brockton","Brookline","Cambridge","Canton","Chelmsford","Chelsea","Chicopee","Danvers","Dartmouth","Dedham","Dracut","Easton","Everett","Fall River","Falmouth","Fitchburg","Framingham","Franklin","Gardner","Gloucester","Haverhill","Holden","Holyoke","Lawrence","Leominster","Lexington","Longmeadow","Lowell","Lynn","Malden","Marlborough","Marshfield","Medford","Melrose","Methuen","Milford","Natick","Needham","New Bedford","Newton","North Andover","North Attleborough","Northampton","Norwood","Peabody","Pittsfield","Plymouth","Quincy","Randolph","Reading","Revere","Salem","Saugus","Shrewsbury","Somerset","Somerville","Springfield","Stoneham","Taunton","Tewksbury","Wakefield","Waltham","Watertown","Wellesley","West Springfield","Westfield","Weymouth","Woburn","Worcester"],
 "Michigan": ["Allen Park","Ann Arbor","Auburn Hills","Battle Creek","Bay City","Birmingham","Burton","Canton","Clinton Township","Dearborn","Dearborn Heights","Detroit","East Lansing","Eastpointe","Farmington Hills","Ferndale","Flint","Garden City","Grand Blanc","Grand Haven","Grand Rapids","Grandville","Holland","Holt","Inkster","Jackson","Kalamazoo","Kentwood","Lansing","Lincoln Park","Livonia","Macomb","Madison Heights","Marquette","Midland","Monroe","Mount Clemens","Mount Pleasant","Muskegon","Northville","Novi","Oak Park","Owosso","Plymouth","Pontiac","Port Huron","Portage","Redford","Rochester Hills","Romulus","Roseville","Royal Oak","Saginaw","Shelby Township","Southfield","Southgate","St. Clair Shores","Sterling Heights","Taylor","Traverse City","Troy","Walker","Warren","Waterford","Wayne","West Bloomfield","Westland","Wyandotte","Wyoming","Ypsilanti"],
 "Minnesota": ["Andover","Anoka","Apple Valley","Bemidji","Blaine","Bloomington","Brooklyn Center","Brooklyn Park","Burnsville","Cambridge","Champlin","Chanhassen","Chaska","Columbia Heights","Coon Rapids","Cottage Grove","Crystal","Duluth","Eagan","East Bethel","Eden Prairie","Edina","Elk River","Faribault","Farmington","Fergus Falls","Forest Lake","Fridley","Golden Valley","Ham Lake","Hastings","Hopkins","Hugo","Hutchinson","Inver Grove Heights","Lakeville","Lino Lakes","Mankato","Maple Grove","Maplewood","Marshall","Minneapolis","Minnetonka","Moorhead","Mounds View","New Brighton","New Hope","New Prague","North Mankato","Northfield","Oak Grove","Oakdale","Otsego","Owatonna","Plymouth","Prior Lake","Ramsey","Red Wing","Richfield","Rochester","Rogers","Rosemount","Roseville","Sartell","Savage","Shakopee","Shoreview","South St. Paul","St. Cloud","St. Louis Park","St. Michael","St. Paul","Stillwater","White Bear Lake","Willmar","Winona","Woodbury"],
 "Mississippi": ["Biloxi","Brandon","Brookhaven","Canton","Clarksdale","Cleveland","Clinton","Columbus","Corinth","D'Iberville","Flowood","Gautier","Greenville","Greenwood","Grenada","Gulf port","Hattiesburg","Hernando","Horn Lake","Jackson","Laurel","Long Beach","Madison","McComb","Meridian","Moss Point","Natchez","Ocean Springs","Olive Branch","Oxford","Pascagoula","Pass Christian","Pearl","Petal","Picayune","Ridgeland","Southaven","Starkville","Tupelo","Vicksburg","West Point","Yazoo City"],
 "Missouri": ["Arnold","Ballwin","Belton","Blue Springs","Cape Girardeau","Chesterfield","Clayton","Columbia","Creve Coeur","Excelsior Springs","Farmington","Ferguson","Florissant","Gladstone","Grandview","Hannibal","Hazelwood","Independence","Jefferson City","Joplin","Kansas City","Kirksville","Kirkwood","Lake St. Louis","Lee's Summit","Liberty","Manchester","Maryland Heights","Mehlville","Nixa","O'Fallon","Ozark","Raymore","Raytown","Republic","Rolla","Sedalia","Springfield","St. Charles","St. Joseph","St. Louis","St. Peters","University City","Warrensburg","Webster Groves","Wentzville","Wildwood"],
 "Montana": ["Belgrade","Billings","Bozeman","Butte","Great Falls","Hamilton","Havre","Helena","Kalispell","Laurel","Lewistown","Livingston","Miles City","Missoula","Polson","Sidney","Whitefish"],
 "Nebraska": ["Beatrice","Bellevue","Columbus","Fremont","Grand Island","Gretna","Hastings","Kearney","La Vista","Lexington","Lincoln","Norfolk","North Platte","Omaha","Papillion","Ralston","Scottsbluff","South Sioux City"],
 "Nevada": ["Boulder City","Carson City","Elko","Enterprise","Fallon","Fernley","Henderson","Las Vegas","Laughlin","Mesquite","North Las Vegas","Pahrump","Paradise","Reno","Sparks","Spring Valley","Summerlin South","Sunrise Manor","Whitney","Winchester"],
 "New Hampshire": ["Bedford","Claremont","Concord","Conway","Derry","Dover","Exeter","Goffstown","Hampton","Hanover","Hooksett","Hudson","Keene","Laconia","Lebanon","Londonderry","Manchester","Merrimack","Milford","Nashua","Pelham","Portsmouth","Rochester","Salem","Somersworth","Windham"],
 "New Jersey": ["Atlantic City","Bayonne","Belleville","Bergenfield","Bloomfield","Brick","Bridgewater","Camden","Cherry Hill","Clifton","Cranford","East Brunswick","East Orange","Edison","Elizabeth","Englewood","Evesham","Ewing","Fair Lawn","Fort Lee","Franklin","Garfield","Gloucester","Hackensack","Hamilton","Harrison","Hoboken","Howell","Irvington","Jackson","Jersey City","Kearny","Lakewood","Linden","Livingston","Lodi","Long Branch","Manalapan","Marlboro","Middletown","Millville","Monroe","Montclair","Moorestown","Morris","Mount Laurel","New Brunswick","Newark","North Bergen","North Brunswick","Nutley","Old Bridge","Orange","Parsippany-Troy Hills","Passaic","Paterson","Piscataway","Perth Amboy","Plainfield","Princeton","Rahway","Ridgewood","Roselle","Sayreville","Scotch Plains","Secaucus","Somerset","South Brunswick","South Orange","Summit","Teaneck","Toms River","Trenton","Union","Union City","Vineland","Wayne","West New York","West Orange","Westfield","Woodbridge"],
 "New Mexico": ["Alamogordo","Albuquerque","Anthony","Artesia","Belen","Carlsbad","Clovis","Deming","Espanola","Farmington","Gallup","Hobbs","Las Cruces","Las Vegas","Los Alamos","Los Lunas","Lovington","Portales","Rio Rancho","Roswell","Ruidoso","Santa Fe","Silver City","Socorro","South Valley","Sunland Park","Taos","Truth or Consequences"],
 "New York": ["Albany","Amherst","Amsterdam","Auburn","Binghamton","Brighton","Bronx","Brooklyn","Buffalo","Centereach","Central Islip","Cheektowaga","Colonie","Commack","Coram","Cortland","East Meadow","Elmira","Freeport","Glen Cove","Hempstead","Hicksville","Huntington","Irondequoit","Ithaca","Jamestown","Kingston","Levittown","Long Beach","Manhattan","Middletown","Mount Vernon","New Rochelle","New York City","Newburgh","Niagara Falls","North Hempstead","Ossining","Peekskill","Poughkeepsie","Queens","Rochester","Rome","Saratoga Springs","Schenectady","Staten Island","Syracuse","Troy","Utica","Valley Stream","Watertown","West Babylon","West Seneca","White Plains","Yonkers"],
 "North Carolina": ["Apex","Asheville","Burlington","Cary","Chapel Hill","Charlotte","Clayton","Concord","Davidson","Durham","Eden","Elizabeth City","Fayetteville","Fuquay-Varina","Garner","Gastonia","Goldsboro","Graham","Greensboro","Greenville","Harrisburg","Hendersonville","Hickory","High Point","Holly Springs","Huntersville","Indian Trail","Jacksonville","Kannapolis","Kernersville","Kinston","Knightdale","Leland","Lexington","Lumberton","Matthews","Mint Hill","Monroe","Mooresville","Morrisville","New Bern","Raleigh","Rocky Mount","Salisbury","Sanford","Shelby","Stallings","Statesville","Thomasville","Wake Forest","Waxhaw","Wilmington","Wilson","Winston-Salem"],
 "North Dakota": ["Bismarck","Devils Lake","Dickinson","Fargo","Grand Forks","Jamestown","Mandan","Minot","Valley City","Wahpeton","Watford City","West Fargo","Williston"],
 "Ohio": ["Akron","Alliance","Ashland","Ashtabula","Athens","Avon","Avon Lake","Barberton","Beavercreek","Boardman","Bowling Green","Broadview Heights","Brook Park","Brunswick","Canton","Centerville","Chillicothe","Cincinnati","Cleveland","Cleveland Heights","Columbus","Cuyahoga Falls","Dayton","Delaware","Dublin","Elyria","Euclid","Fairborn","Fairfield","Findlay","Gahanna","Green","Grove City","Hamilton","Hilliard","Huber Heights","Hudson","Kent","Kettering","Lakewood","Lancaster","Lebanon","Lima","Lorain","Mansfield","Marion","Mason","Massillon","Maumee","Medina","Mentor","Miamisburg","Middletown","Newark","North Olmsted","North Ridgeville","North Royalton","Norwalk","Oregon","Oxford","Parma","Perrysburg","Pickerington","Powell","Reynoldsburg","Sandusky","Sidney","Solon","Springfield","Stow","Strongsville","Sylvania","Toledo","Trotwood","Troy","Twinsburg","Upper Arlington","Wadsworth","Warren","Westerville","Westlake","Wooster","Xenia","Youngstown","Zanesville"],
 "Oklahoma": ["Ada","Altus","Ardmore","Bartlesville","Bethany","Bixby","Blanchard","Broken Arrow","Chickasha","Choctaw","Claremore","Del City","Duncan","Durant","Edmond","El Reno","Elk City","Enid","Glenpool","Guthrie","Jenks","Lawton","McAlester","Miami","Midwest City","Moore","Muskogee","Mustang","Newcastle","Norman","Oklahoma City","Owasso","Ponca City","Sand Springs","Sapulpa","Shawnee","Stillwater","Tahlequah","The Village","Tulsa","Weatherford","Woodward","Yukon"],
 "Oregon": ["Albany","Aloha","Ashland","Beaverton","Bend","Bethany","Canby","Cedar Hills","Cedar Mill","Central Point","Coos Bay","Corvallis","Cottage Grove","Dallas","Eugene","Forest Grove","Four Corners","Gladstone","Grants Pass","Gresham","Happy Valley","Hayesville","Hermiston","Hillsboro","Hood River","Keizer","Klamath Falls","La Grande","Lake Oswego","Lebanon","McMinnville","Medford","Milwaukie","Newberg","Newport","Oak Grove","Oregon City","Pendleton","Portland","Redmond","Roseburg","Salem","Sandy","Sherwood","Springfield","Tigard","Troutdale","Tualatin","West Linn","Wilsonville","Woodburn"],
 "Pennsylvania": ["Abington","Allentown","Altoona","Bethel Park","Bethlehem","Bucks","Butler","Carlisle","Chambersburg","Chester","Cranberry","Drexel Hill","Easton","Erie","Harrisburg","Haverford","Hazleton","Hershey","Horsham","King of Prussia","Lancaster","Lansdale","Lebanon","Levittown","Lower Merion","McCandless","Mechanicsburg","Monroeville","Mount Lebanon","Murrysville","Norristown","Penn Hills","Philadelphia","Pittsburgh","Plum","Pottstown","Pottsville","Radnor","Reading","Ross","Scranton","Shaler","Springfield","State College","Warminster","West Chester","West Mifflin","Whitehall","Wilkes-Barre","Williamsport","York"],
 "Rhode Island": ["Barrington","Bristol","Central Falls","Coventry","Cranston","Cumberland","East Greenwich","East Providence","Johnston","Lincoln","Middletown","Narragansett","Newport","North Kingstown","North Providence","Pawtucket","Providence","Smithfield","South Kingstown","Warwick","West Warwick","Westerly","Woonsocket"],
 "South Carolina": ["Aiken","Anderson","Beaufort","Bluffton","Cayce","Charleston","Clemson","Columbia","Conway","Easley","Florence","Fort Mill","Goose Creek","Greenville","Greenwood","Greer","Hanahan","Hilton Head Island","Irmo","Lexington","Mauldin","Mount Pleasant","Murrells Inlet","Myrtle Beach","North Augusta","North Charleston","North Myrtle Beach","Orangeburg","Rock Hill","Simpsonville","Spartanburg","Summerville","Sumter","Taylors","West Columbia"],
 "South Dakota": ["Aberdeen","Box Elder","Brandon","Brookings","Harrisburg","Huron","Madison","Mitchell","Pierre","Rapid City","Sioux Falls","Spearfish","Sturgis","Tea","Vermillion","Watertown","Yankton"],
 "Tennessee": ["Bartlett","Brentwood","Bristol","Chattanooga","Clarksville","Cleveland","Collierville","Columbia","Cookeville","Crossville","Dyersburg","East Ridge","Farragut","Franklin","Gallatin","Germantown","Goodlettsville","Greeneville","Hendersonville","Jackson","Johnson City","Kingsport","Knoxville","La Vergne","Lakeland","Lebanon","Maryville","McMinnville","Memphis","Morristown","Mount Juliet","Murfreesboro","Nashville","Nolensville","Oak Ridge","Portland","Sevierville","Shelbyville","Smyrna","Spring Hill","Springfield","Tullahoma"],
 "Texas": ["Abilene","Allen","Amarillo","Arlington","Austin","Baytown","Beaumont","Bedford","Brownsville","Bryan","Burleson","Carrollton","Cedar Hill","Cedar Park","Channelview","Cinco Ranch","Cleburne","College Station","Conroe","Converse","Coppell","Copperas Cove","Corpus Christi","Dallas","Deer Park","Del Rio","Denton","DeSoto","Duncanville","Eagle Pass","Edinburg","El Paso","Euless","Flower Mound","Forney","Fort Worth","Frisco","Galveston","Garland","Georgetown","Grand Prairie","Grapevine","Greenville","Haltom City","Harlingen","Houston","Humble","Huntsville","Hurst","Irving","Katy","Keller","Killeen","Kingsville","Kyle","La Porte","Lake Jackson","Lancaster","Laredo","League City","Leander","Lewisville","Little Elm","Longview","Lubbock","Lufkin","Mansfield","McAllen","McKinney","Mesquite","Midland","Mission","Missouri City","Murphy","Nacogdoches","New Braunfels","North Richland Hills","Odessa","Pasadena","Pearland","Pflugerville","Pharr","Plano","Port Arthur","Portland","Prosper","Richardson","Rockwall","Rosenberg","Round Rock","Rowlett","Royse City","San Angelo","San Antonio","San Juan","San Marcos","Schertz","Seguin","Sherman","Socorro","Southlake","Spring","Stafford","Sugar Land","Temple","Texarkana","Texas City","The Colony","The Woodlands","Tyler","Universal City","Victoria","Waco","Watauga","Waxahachie","Weatherford","Webster","Weslaco","Wichita Falls","Wylie"],
 "Utah": ["American Fork","Bluffdale","Bountiful","Brigham City","Cedar City","Centerville","Clearfield","Clinton","Cottonwood Heights","Draper","Eagle Mountain","Farmington","Herriman","Highland","Holladay","Kaysville","Kearns","Layton","Lehi","Logan","Magna","Mapleton","Midvale","Millcreek","Murray","North Ogden","North Salt Lake","Ogden","Orem","Payson","Pleasant Grove","Provo","Riverton","Roy","Salt Lake City","Sandy","Saratoga Springs","South Jordan","South Ogden","South Salt Lake","Spanish Fork","Springville","St. George","Syracuse","Taylorsville","Tooele","West Haven","West Jordan","West Valley City","Woods Cross"],
 "Vermont": ["Barre","Bennington","Brattleboro","Burlington","Colchester","Essex","Essex Junction","Hartford","Jericho","Middlebury","Milton","Montpelier","Morristown","Northfield","Rutland","Shelburne","South Burlington","Springfield","St. Albans","St. Johnsbury","Swanton","Vergennes","Williston","Winooski"],
 "Virginia": ["Alexandria","Annandale","Arlington","Ashburn","Bailey's Crossroads","Blacksburg","Bristol","Burke","Cave Spring","Centreville","Charlottesville","Chesapeake","Christiansburg","Dale City","Danville","Fairfax","Falls Church","Fredericksburg","Gainesville","Glen Allen","Hampton","Harrisonburg","Herndon","Leesburg","Lynchburg","Manassas","Mechanicsville","Midlothian","Newport News","Norfolk","Petersburg","Portsmouth","Reston","Richmond","Roanoke","Salem","Short Pump","Springfield","Stafford","Staunton","Sterling","Suffolk","Tuckahoe","Tysons","Virginia Beach","Waynesboro","Williamsburg","Winchester","Woodbridge"],
 "Washington": ["Auburn","Bainbridge Island","Battle Ground","Bellevue","Bellingham","Bonney Lake","Bothell","Bremerton","Burien","Burlington","Camas","Centralia","Covington","Des Moines","East Wenatchee","Edmonds","Ellensburg","Enumclaw","Everett","Federal Way","Issaquah","Kenmore","Kennewick","Kent","Kirkland","Lacey","Lake Forest Park","Lake Stevens","Lakewood","Longview","Lynden","Lynnwood","Maple Valley","Marysville","Mercer Island","Mill Creek","Monroe","Moses Lake","Mount Vernon","Mountlake Terrace","Mukilteo","Oak Harbor","Olympia","Pasco","Pullman","Puyallup","Redmond","Renton","Richland","Sammamish","SeaTac","Seattle","Shoreline","Silverdale","Snoqualmie","Spokane","Spokane Valley","Tacoma","Tukwila","Tumwater","University Place","Vancouver","Walla Walla","Washougal","Wenatchee","Woodinville","Yakima"],
 "West Virginia": ["Barboursville","Beckley","Bluefield","Bridgeport","Charleston","Clarksburg","Cross Lanes","Dunbar","Elkins","Fairmont","Huntington","Hurricane","Martinsburg","Morgantown","Moundsville","Nitro","Parkersburg","Princeton","South Charleston","St. Albans","Teays Valley","Vienna","Weirton","Wheeling"],
 "Wisconsin": ["Appleton","Bellevue","Beloit","Brookfield","Brown Deer","Burlington","Caledonia","Cudahy","De Pere","Eau Claire","Fitchburg","Fond du Lac","Franklin","Germantown","Grand Chute","Green Bay","Greendale","Greenfield","Howard","Janesville","Kaukauna","Kenosha","La Crosse","Madison","Manitowoc","Marshfield","Menasha","Menomonee Falls","Mequon","Middleton","Milwaukee","Mount Pleasant","Muskego","Neenah","New Berlin","Oak Creek","Oconomowoc","Oshkosh","Pleasant Prairie","Racine","Sheboygan","South Milwaukee","Stevens Point","Sun Prairie","Superior","Waukesha","Wausau","Wauwatosa","West Allis","West Bend","Whitefish Bay","Wisconsin Rapids"],
 "Wyoming": ["Casper","Cheyenne","Cody","Douglas","Evanston","Gillette","Green River","Jackson","Lander","Laramie","Powell","Rawlins","Riverton","Rock Springs","Sheridan","Torrington","Worland"],
};
